// <auto-generated />
using System;
using LocalBusiness.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocalBusinessLookup.Migrations
{
    [DbContext(typeof(LocalBusinessContext))]
    [Migration("20240705172937_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LocalBusiness.Business", b =>
                {
                    b.Property<int>("BusinessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("BusinessId");

                    b.ToTable("Businesses");

                    b.HasData(
                        new
                        {
                            BusinessId = 1,
                            DateAdded = new DateTime(2024, 7, 5, 17, 29, 37, 392, DateTimeKind.Utc).AddTicks(2889),
                            Description = "BBQ of all forms!",
                            Name = "Jim's Roadhouse",
                            Type = "Restaurant"
                        },
                        new
                        {
                            BusinessId = 2,
                            DateAdded = new DateTime(2024, 7, 5, 17, 29, 37, 392, DateTimeKind.Utc).AddTicks(2891),
                            Description = "We got all kinds of tools!",
                            Name = "Terry's Tools",
                            Type = "Shop"
                        },
                        new
                        {
                            BusinessId = 3,
                            DateAdded = new DateTime(2024, 7, 5, 17, 29, 37, 392, DateTimeKind.Utc).AddTicks(2891),
                            Description = "Don't step foot in the place.",
                            Name = "Parker's Place",
                            Type = "Place"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
